name: Publish on Docker Hub and Deploy

on:
  release:
    types: [published]

jobs:
  run_pub_tests:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: 'arm'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: echo workspace
        run: echo $GITHUB_WORKSPACE
        shell: bash
      - name: Run tests
        run: coverage run src/app_test.py
      - name: Tests report
        run: coverage report
  build_and_pub:
    needs: [run_pub_tests]
    runs-on: [self-hosted]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login --username ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:10} -f Dockerfile .
      - name: Push image tag to docker.io
        run: docker push $LOGIN/$NAME:${GITHUB_REF:10}
      - name: Tag last release as latest
        run: docker tag $LOGIN/$NAME:${GITHUB_REF:10} $LOGIN/$NAME:latest
      - name: Push image tag latest to docker.io
        run: docker push $LOGIN/$NAME:latest